version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: aline-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - aline-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aline-api
    expose:
      - "8000"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Seoul
    command: sh -c "ENV=prod uv run main.py"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - aline-network


  mongodb:
    build:
      context: ./mongo_db
      dockerfile: Dockerfile
    container_name: aline-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped
    networks:
      - aline-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  aline-network:
    driver: bridge

volumes:
  mongodb_data:
